name: Daily Stats Collection for nm-testing

on:
  schedule:
    - cron: '10 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:

jobs:
  collect_stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_GITHUB_ACTION }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect stats for nm-testing
        run: |
          python scripts/get_author_model_stats.py --author nm-testing
          python scripts/calc_delta.py --file model_stats_nm-testing.csv

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add model_stats*
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update nm-testing stats $(date +'%Y-%m-%d')" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_ACTION }}
